@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{

Class UniqueStudentList
Class Course
Class CourseName
Class Student
Class Name
Class Email
Class Remark
Class Tag

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Course

Course *-down-> CourseName
Course *-down-> UniqueStudentList
CourseName -[hidden]right->UniqueStudentList
Course --> "~* filtered" Student
UniqueStudentList --> "*" Student
Student *-down-> Name
Student *-down-> Email
Student *-down-> Remark
Student *-down-> "*" Tag

@enduml
